In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.10.4


In [2]:
# Para atualizar um pacote, execute o comando abaixo no terminal ou prompt de comando:
# pip install -U nome_pacote

# Para instalar a versão exata de um pacote, execute o comando abaixo no terminal ou prompt de comando:
#!pip install nome_pacote==versão_desejada

# Depois de instalar ou atualizar o pacote, reinicie o jupyter notebook.

# Instala o pacote watermark.
# Esse pacote é usado para gravar as versões de outros pacotes usados neste jupyter notebook.
#!pip install -q -U watermark

In [3]:
# Importando o módulo NumPy
import numpy as np

In [4]:
# Versões dos pacotes usados neste jupyter notebook
%reload_ext watermark
%watermark -a "John Costa" --iversions

Author: John Costa

sys  : 3.10.4 | packaged by conda-forge | (main, Mar 30 2022, 08:38:02) [MSC v.1916 64 bit (AMD64)]
numpy: 1.22.3



In [5]:
import warnings
warnings.filterwarnings('ignore')

In [6]:
# Configuração de impressão do NumPy
np.set_printoptions(suppress = True, linewidth = 200, precision = 2)

# Carregando o Dataset

In [7]:
dados = np.genfromtxt("Dados/dataset1.csv",
                      delimiter = ';',
                      skip_header = 1,
                      autostrip = True,
                      encoding = 'cp1252'
                      )

In [8]:
type(dados)

numpy.ndarray

In [9]:
dados.shape

(10000, 14)

In [10]:
dados.view()

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

Observe como várias colunas estão com o tipo nan. Isso se deve a racteres especiais no conjunto

# Verificando Valores Ausentes

In [11]:
np.isnan(dados).sum()

88005

In [12]:
# Vamos retornar o maior valor + 1 ignorando valores nan
# Usares esse valor arbitrário para preencher os valores ausentes no momento da carga de dados de variáveis
# numéricos e depos tratamos esse valor como valor ausente
valor_coringa = np.nanmax(dados) + 1
print(valor_coringa)

68616520.0


In [13]:
# Calculamos a média (variáveis numéricas) ignorando valores nan por coluna
# Usaremos isso para seprar variáveis numéricas de variáveis do tipo string
media_ignorando_nan = np.nanmean(dados, axis = 0)
print(media_ignorando_nan)

[54015809.19         nan    15273.46         nan    15311.04         nan       16.62      440.92         nan         nan         nan         nan         nan     3143.85]


In [14]:
# Colunas do tipo string com valores ausentes
colunas_strings = np.argwhere(np.isnan(media_ignorando_nan)).squeeze()
colunas_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [15]:
# Colunas do tipo numérico
colunas_numericas = np.argwhere(np.isnan(media_ignorando_nan) == False).squeeze()
colunas_numericas

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

Importando novamente o dataset, separando colunas do tipo string de colunas numéricas.

In [16]:
# Carrega as colunas do tipo string
arr_string = np.genfromtxt("Dados/dataset1.csv",
                           delimiter=";",
                           skip_header=1,
                           autostrip=True,
                           usecols=colunas_strings,
                           dtype=str,
                           encoding = 'cp1252'
                           )

In [17]:
arr_string

array([['May-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']], dtype='<U69')

In [18]:
# Carrega as colunas do tipo numérico
arr_numeric = np.genfromtxt("Dados/dataset1.csv",
                           delimiter=";",
                           skip_header=1,
                           autostrip=True,
                           usecols=colunas_numericas,
                           filling_values=valor_coringa,
                           encoding = 'cp1252'
                           )

In [19]:
arr_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

Agora extraímos os nomes das colunas.

In [20]:
# Carrega os nomes das colunas
arr_nomes_colunas = np.genfromtxt("Dados/dataset1.csv",
                            delimiter=";",
                            autostrip=True,
                            skip_footer=dados.shape[0],
                            dtype= str,
                            encoding = 'cp1252'
                           )

In [21]:
arr_nomes_colunas

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state', 'total_pymnt'], dtype='<U19')

In [22]:
# Separa cabeçalho de colunas numéricas e string
header_strings, header_numeric = arr_nomes_colunas[colunas_strings], arr_nomes_colunas[colunas_numericas]

In [23]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [24]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

# Função de Checkpoint
## Checkpoint 1
Vamos criar uma função de checkpoint para salvar os resultados intermediários.

In [25]:
# Função
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

In [26]:
checkpoint_inicial = checkpoint("Dados/Checkpoint-Inicial", header_strings, arr_string)

In [27]:
checkpoint_inicial['data']

array([['May-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']], dtype='<U69')

In [28]:
np.array_equal(checkpoint_inicial['data'], arr_string)

True

# Manipulando as Colunas do Tipo String

In [29]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [ ]:
# Vamos ajustar o nome da coluna issue_d para facilitar a identificação da coluna
header_strings[0] = 'issue_date'

In [ ]:
header_strings

In [ ]:
arr_string

## Pré-Processamento da Variável issue_date com Label Encoding

In [ ]:
# Extrai os valores únicos da variável
np.unique(arr_string[:,0])

In [ ]:
# Vamos remover o sufixo -15 e converter em um array de strings
arr_string[:,0] = np.chararray.strip(arr_string[:,0], "-15")

In [ ]:
# Extrai os valores únicos da variável
np.unique(arr_string[:,0])

In [ ]:
# Criamos um array com os meses (incluindo um elemento como vazio para o que estiver em branco
meses = np.array(['','Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

In [ ]:
# Loop ára converter os nomes dos meses em valores numéricos
# Chamamos isso de label encoding
for i in range(13):
    arr_string[:,0] = np.where(arr_string[:,0] == meses[i], i, arr_string[:,0])

In [ ]:
np.unique(arr_string[:,0])

# Pré-Processamento da Variável loan_status com binarização

In [ ]:
header_strings

In [ ]:
# Extrai os valores únicos da variável
np.unique(arr_string[:,1])

In [ ]:
# Números de elementos
np.unique(arr_string[:,1]).size

In [ ]:
# Criamos um array com apenas 3 status
status_bad = np.array(['', 'Charged Off', 'Default', 'Late (31-120 days'])

In [ ]:
# Checamos agora os valores da variável e comparamos com o array anterior convertendo a variável para valores binários
# Chamamos isso de binarização
arr_string[:,1] = np.where(np.isin(arr_string[:,1], status_bad),0,1)

In [ ]:
# Extrai os valores únicos da variável
np.unique(arr_string[:,1])

# Pré-Processamento da Variável term com Limpeza de String

In [ ]:
header_strings

In [ ]:
# Extrai os valores únicos da variável
np.unique(arr_string[:,2])

In [ ]:
# Removemos a palavra months (observe o espaço antes da palavra)
arr_string[:,2] = np.chararray.strip(arr_string[:,2], " months")
arr_string[:,2]

In [ ]:
# Mudamos o título da variável
header_strings[2] = "term_months"

In [ ]:
# Substituímos os valores ausentes pelo maior valor, em nosso caso 60
arr_string[:,2] = np.where(arr_string[:,2] == '', '60', arr_string[:,2])

In [ ]:
arr_string[:,2]

In [ ]:
# Extrai os valores únicos da variável
np.unique(arr_string[:,2])

# Pré-Processamento das Variáveis grade e sub_grade com Dicionário (Tipo de Label Encoding)

In [ ]:
header_strings

In [ ]:
# Extrai os valores únicos da variável
np.unique(arr_string[:,3])

In [ ]:
# Extrai os valores únicos da variável
np.unique(arr_string[:,4])

Vamos ajustar a variável sub_grade

In [ ]:
np.unique(arr_string[:,3])

In [ ]:
np.unique(arr_string[:,3])[1:]

In [ ]:
# Loop para ajuste da variável sub_grade
# Checa se sub_grade é null e se o valor de grade é igual o item do loop, se for ele concatena i+'5', senão ele mantem o valor
for i in np.unique(arr_string[:,3])[1:]:
    arr_string[:,4] = np.where((arr_string[:,4] == '') & (arr_string[:,3] == i), i + '5', arr_string[:,4])

In [ ]:
# Retornando categorias e suas respectivas contagens
np.unique(arr_string[:,4], return_counts = True)

In [ ]:
# Substituímos valores ausentes por uma nova categoria
arr_string[:,4] = np.where(arr_string[:,4] == '', 'H1', arr_string[:,4])

In [ ]:
# Extrai os valores únicos da variável
np.unique(arr_string[:,4])

Vamos remover a variável grade.

In [ ]:
# Não precisamos mais davariável garde. Podemos removê-la.
arr_string = np.delete(arr_string, 3, axis = 1)

In [ ]:
# Nova variável na colina de índice 3
arr_string[:,3]

In [ ]:
# não podemos esquece de remover a coluna do array de nomes de colunas
header_strings = np.delete(header_strings, 3)

In [ ]:
# Nova variável na coluna de índice 3
header_strings[3]

Por fim, convertemos a variável sub_grade para sua representação numérica.

In [ ]:
# Extrai os valores únicos da variável
np.unique(arr_string[:,3])

In [ ]:
# Cria uma lista da chaves
keys = list(np.unique(arr_string[:,3]))
keys[0]

In [ ]:
# Cria uma lista de valores
values = list(range(1, np.unique(arr_string[:,3]).shape[0] + 1))
values[0]

In [ ]:
# Criamos então o dicionário
dict_sub_grade = dict(zip(keys, values))

In [ ]:
dict_sub_grade

In [ ]:
# Loop ára substituit a string com as categorias pela representação numérica (frequência)
for i in np.unique(arr_string[:,3]):
    arr_string[:,3] = np.where(arr_string[:,3] == i, dict_sub_grade[i], arr_string[:,3])

In [ ]:
# Extra os valores únicos da variável
np.unique(arr_string[:,3])

# Pré-Processamento da Variável Verification status com Binarização

In [ ]:
# Lista com os nomes da variáveis
header_strings

In [ ]:
# Extrai os valores únicos da variável
np.unique(arr_string[:,4])

In [ ]:
# Usamos a binarização nesta variável
arr_string[:,4] = np.where((arr_string[:,4] == '') | (arr_string[:,4] == 'Not Verified'), 0, 1)

In [ ]:
# Extrai os valores únicos da variável
np.unique(arr_string[:,4])

# Pré-Processamento da Variável url com Extração de ID

In [ ]:
# Visualiza amostra dos dados
arr_string[:,5]

In [ ]:
# Extraímos o id no final de cada url
np.chararray.strip(arr_string[:,5], "https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

In [ ]:
# Substituímos a url pelo valor do id na url
arr_string[:,5] = np.chararray.strip(arr_string[:,5], "https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

In [ ]:
# Convertemos o tipo para int32
arr_string[:,5].astype(dtype= np.int32)

In [ ]:
# Parece que esse id está presente na primeira coluna do conjunto de dados.
# Vamos converter para int 32 e comparar
arr_numeric[:,0].astype(dtype = np.int32)

In [ ]:
np.array_equal(arr_numeric[:,0].astype(dtype=np.int32), arr_string[:,5].astype(dtype=np.int32))

Sim, é a mesma informação. Vamos então remover uma das colunas.

In [ ]:
# Remove do array de dados
arr_string = np.delete(arr_string, 5, axis=1)

In [ ]:
# Remove do array de nome de coluna
header_strings = np.delete(header_strings, 5)

In [ ]:
# Nova coluna no índice 5
arr_string[:,5]

In [ ]:
# Nova lista de colunas
header_strings

In [ ]:
# Coluna ud
arr_numeric[:,0]

In [ ]:
# coluna id agora faz parte do array de numéricos
header_numeric

# Pré-Processamento da Variável address com Categorização

In [ ]:
header_strings

In [ ]:
# Vamos ajustar o nome da coluna
header_strings[5] = "state_address"

In [ ]:
# Extrai nome e contagens
states_names, states_count = np.unique(arr_string[:,5], return_counts = True)

In [ ]:
# Ordena em ordem descrescente
states_count_sorted = np.argsort(-states_count)

In [ ]:
# Imprime o resultado
states_names[states_count_sorted], states_count[states_count_sorted]

In [ ]:
# Substituímos valores ausentes por zero
arr_string[:,5] = np.where(arr_string[:,5] == '', 0, arr_string[:,5])

Vamos separar os estads por regiões.

In [ ]:
# Separamos os estados por regiões
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [ ]:
# Agora substituímos cada estado pelo id da sua região
arr_string[:,5] = np.where(np.isin(arr_string[:,5], states_west), 1, arr_string[:,5])
arr_string[:,5] = np.where(np.isin(arr_string[:,5], states_south), 2, arr_string[:,5])
arr_string[:,5] = np.where(np.isin(arr_string[:,5], states_midwest), 3, arr_string[:,5])
arr_string[:,5] = np.where(np.isin(arr_string[:,5], states_east), 4, arr_string[:,5])

In [ ]:
# Extrai os valores únicos
np.unique(arr_string[:,5])

**Você pode modificar os dados, mas não pode modificar a informação!**

## Convertendo o Array

Nosso array de strings agora é um array numérico. Vamos ajustar o tipo de dado.

In [ ]:
arr_string

In [ ]:
arr_string = arr_string.astype(int)

In [ ]:
arr_string

In [ ]:
arr_string.dtype

## Checkpoint com Variáveis do Tipo String Limpas e Pré-Processadas

**Checkpoint 2**

Concluída a primeira parte, vamos gravar o checkpooint.

In [ ]:
checkpooint_strings = checkpoint("Dados/Checkpoint-Strings", header_strings, arr_string)

In [ ]:
checkpooint_strings["header"]

In [ ]:
checkpooint_strings["data"]

In [ ]:
np.array_equal(checkpooint_strings["data"], arr_string)

# Manipulando Colunas Numéricas

In [ ]:
# Visualiza os dados
arr_numeric

In [ ]:
# nomes das colunas
header_numeric

In [ ]:
# Não temos valor ausente, pois ao carregar os dados substituídos por um valor arbitrário
np.isnan(arr_numeric).sum()

In [ ]:
valor_coringa

In [ ]:
# Podemos checar se uma coluna foi preenchida com o valor coringa
np.isin(arr_numeric[:,0], valor_coringa)

In [ ]:
# Podemos checar se uma coluna foi preenchida com o valor coringa
np.isin(arr_numeric[:,0], valor_coringa).sum()

Vamos criar um array de estatística, especificamente valor mínimo, máximo e média de cada variável. Usaremos isso no tratament de valores ausentes (preenchidos com o valor coringa).

In [ ]:
# Criamos um array com valor mínimo, média e valor máximo ignorando nan
# Usaremos isso no tratamento de valores ausentes
arr_stats = np.array([np.nanmin(dados, axis = 0), media_ignorando_nan, np.nanmax(dados, axis = 0)])


In [ ]:
print(arr_stats)

In [ ]:
arr_stats[:, colunas_numericas]

# Pré-Processamento da Variável funded_amnt

In [ ]:
# Visualiza os dados
arr_numeric[:,2]

In [ ]:
arr_stats[0, colunas_numericas[2]]

In [ ]:
# Ajustamos o conteúdo da coluna
arr_numeric[:,2] = np.where(arr_numeric[:,2] == valor_coringa, arr_stats[0, colunas_numericas[2]], arr_numeric[:,2])

In [ ]:
arr_numeric[:,2]

# Pré-Processamento das Variáveis loan_amnt, int_rate, installment e total_pymnt

In [ ]:
# Nomes das colunas
header_numeric

In [ ]:
# Loop para substituir o valor ausente (valor-coringa) pelos valores do array de estatísticas
for i in [1,3,4,5]:
    arr_numeric[:,i] = np.where(arr_numeric[:,i] == valor_coringa,
                                arr_stats[2, colunas_numericas[i]],
                                arr_numeric[:,i])

In [ ]:
arr_numeric

# Trabalhando com o Segundo Dataset
vamos carregar os dados de cotação USD - EURO. Cada linha do dataset corresponde à taxa de câmbio para um ês em um ano.

In [ ]:
# Carrega o segundo dataset
dados_cot = np.genfromtxt("Dados/dataset2.csv",
                            delimiter = ',',
                            autostrip = True,
                            skip_header = 1,
                            usecols = 3)

In [ ]:
# Visualiza
dados_cot

In [ ]:
# nomes de colunas
header_strings

In [ ]:
# Dados
arr_string

In [ ]:
# A coluna 0 do array de strings é o mês
arr_string[:,0]

In [ ]:
# Vamos atribuir a coluna de mês à variável chama exchange_rate
exchange_rate = arr_string[:,0]

In [ ]:
exchange_rate

In [ ]:
# Loop para preeencher a variável enchange_rate com a taxa correspondente ao mês
# Usamos dados_cot[i - 1] devido a forma como carregamos os meses para ciomportar o zero
for i in range(1, 13):
    exchange_rate = np.where(exchange_rate == i, dados_cot[i - 1], exchange_rate)

In [ ]:
exchange_rate

In [ ]:
# Onde a taxa de câmbio estiver com zero substituiímos pela média
exchange_rate = np.where(exchange_rate == 0, np.mean(dados_cot), exchange_rate)

In [ ]:
exchange_rate

In [ ]:
exchange_rate.shape

In [ ]:
arr_numeric.shape

In [ ]:
exchange_rate = np.reshape(exchange_rate, (10000,1))

In [ ]:
# Concatenação dos arrays
arr_numeric = np.hstack((arr_numeric, exchange_rate))

In [ ]:
# Inclui o nome da coluno no array de nomes de colunas
header_numeric = np.concatenate((header_numeric, np.array(['exchange_rate'])))

In [ ]:
header_numeric

Vamos criar colunas para as taxas de câmbio em USD e EURO

In [ ]:
header_numeric

In [ ]:
# Colunas em USD
columns_dollar = np.array([1,2,4,5])

In [ ]:
# Visualiza
arr_numeric[:,6]

In [ ]:
# Shape
arr_numeric.shape

In [ ]:
# Loop pelas colunas USD para aplicar a taxa de conversão para EURO
for i in columns_dollar:
    arr_numeric = np.hstack((arr_numeric, np.reshape(arr_numeric[:,i] / arr_numeric[:,6], (10000,1))))

In [ ]:
# Shape
arr_numeric.shape

In [ ]:
# Visualiza
arr_numeric

Vamos expandir o cabeçalho com as novas colunas.

In [ ]:
header_additional = np.array([column_name + '_EURO' for column_name in header_numeric[columns_dollar]])

In [ ]:
header_additional

In [ ]:
header_numeric = np.concatenate((header_numeric, header_additional))

In [ ]:
header_numeric

In [ ]:
header_numeric[columns_dollar] = np.array([column_name + '_USD' for column_name in header_numeric[columns_dollar]])

In [ ]:
header_numeric

In [ ]:
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [ ]:
header_numeric = header_numeric[columns_index_order]

In [ ]:
arr_numeric

In [ ]:
arr_numeric = arr_numeric[:, columns_index_order]

In [ ]:
arr_numeric

# Pré-Processamento da Variável int_rate

In [ ]:
header_numeric

In [ ]:
arr_numeric[:,5]

In [ ]:
# Vamos apenas dividir por 100
arr_numeric[:,5] = arr_numeric[:,5] / 100

In [ ]:
arr_numeric[:,5]

# Checkpoint com Variáveis Numéricas Limpas e Pré-Processadas
Checkpoint 3

In [ ]:
checkpoint_numeric = checkpoint("Dados/Checkpoint-Numeric", header_numeric, arr_numeric)

In [ ]:
checkpoint_numeric['header'], checkpoint_numeric['data']

# Construindo o Dataset Final

In [ ]:
checkpooint_strings['data'].shape

In [ ]:
checkpoint_numeric['data'].shape

In [ ]:
# Concatena os arrays
df_final = np.hstack((checkpoint_numeric['data'], checkpooint_strings['data']))

In [ ]:
df_final

In [ ]:
# Verifica se tem valor ausente
np.isnan(df_final).sum()

In [ ]:
# Cancatena os arrays de nomes de colunas
header_full = np.concatenate((checkpoint_numeric['header'], checkpooint_strings['header']))

In [ ]:
#Ordenando o dataset
df_final = df_final[np.argsort(df_final[:,0])]

In [ ]:
df_final

In [ ]:
# Conferindo a ordenação da coluna 0
np.argsort(df_final[:,0])

# Gravando o Dataset Final Limpo e Pré-Processado

In [ ]:
# Concatena o array de nome de colunas com o array de dados
df_final = np.vstack((header_full, df_final))

In [ ]:
# Salva em disco
np.savetxt("Dados/dataset_limpo_preprocessado.csv",
            df_final,
            fmt = '%s',
            delimiter=',')

# Fim

In [32]:
arr_string

array([['May-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']], dtype='<U69')

## Pré-Processamento da Variável issue_date com Label Encoding

In [33]:
# Extrai os valores únicos da variável
np.unique(arr_string[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15', 'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [34]:
# Vamos remover o sufixo -15 e converter em um array de strings
arr_string[:,0] = np.chararray.strip(arr_string[:,0], "-15")

In [35]:
# Extrai os valores únicos da variável
np.unique(arr_string[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'], dtype='<U69')

In [36]:
# Criamos um array com os meses (incluindo um elemento como vazio para o que estiver em branco
meses = np.array(['','Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

In [37]:
# Loop ára converter os nomes dos meses em valores numéricos
# Chamamos isso de label encoding
for i in range(13):
    arr_string[:,0] = np.where(arr_string[:,0] == meses[i], i, arr_string[:,0])

In [38]:
np.unique(arr_string[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

# Pré-Processamento da Variável loan_status com binarização

In [39]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [40]:
# Extrai os valores únicos da variável
np.unique(arr_string[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued', 'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [41]:
# Números de elementos
np.unique(arr_string[:,1]).size

9

In [42]:
# Criamos um array com apenas 3 status
status_bad = np.array(['', 'Charged Off', 'Default', 'Late (31-120 days'])

In [43]:
# Checamos agora os valores da variável e comparamos com o array anterior convertendo a variável para valores binários
# Chamamos isso de binarização
arr_string[:,1] = np.where(np.isin(arr_string[:,1], status_bad),0,1)

In [44]:
# Extrai os valores únicos da variável
np.unique(arr_string[:,1])

array(['0', '1'], dtype='<U69')

# Pré-Processamento da Variável term com Limpeza de String

In [45]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [46]:
# Extrai os valores únicos da variável
np.unique(arr_string[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [47]:
# Removemos a palavra months (observe o espaço antes da palavra)
arr_string[:,2] = np.chararray.strip(arr_string[:,2], " months")
arr_string[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [48]:
# Mudamos o título da variável
header_strings[2] = "term_months"

In [49]:
# Substituímos os valores ausentes pelo maior valor, em nosso caso 60
arr_string[:,2] = np.where(arr_string[:,2] == '', '60', arr_string[:,2])

In [50]:
arr_string[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [51]:
# Extrai os valores únicos da variável
np.unique(arr_string[:,2])

array(['36', '60'], dtype='<U69')

# Pré-Processamento das Variáveis grade e sub_grade com Dicionário (Tipo de Label Encoding)

In [52]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [53]:
# Extrai os valores únicos da variável
np.unique(arr_string[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [54]:
# Extrai os valores únicos da variável
np.unique(arr_string[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1',
       'G2', 'G3', 'G4', 'G5'], dtype='<U69')

Vamos ajustar a variável sub_grade

In [55]:
np.unique(arr_string[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [56]:
np.unique(arr_string[:,3])[1:]

array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [57]:
# Loop para ajuste da variável sub_grade
# Checa se sub_grade é null e se o valor de grade é igual o item do loop, se for ele concatena i+'5', senão ele mantem o valor
for i in np.unique(arr_string[:,3])[1:]:
    arr_string[:,4] = np.where((arr_string[:,4] == '') & (arr_string[:,3] == i), i + '5', arr_string[:,4])

In [58]:
# Retornando categorias e suas respectivas contagens
np.unique(arr_string[:,4], return_counts = True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1',
        'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5], dtype=int64))

In [59]:
# Substituímos valores ausentes por uma nova categoria
arr_string[:,4] = np.where(arr_string[:,4] == '', 'H1', arr_string[:,4])

In [60]:
# Extrai os valores únicos da variável
np.unique(arr_string[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2',
       'G3', 'G4', 'G5', 'H1'], dtype='<U69')

Vamos remover a variável grade.

In [61]:
# Não precisamos mais davariável garde. Podemos removê-la.
arr_string = np.delete(arr_string, 3, axis = 1)

In [62]:
# Nova variável na colina de índice 3
arr_string[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [63]:
# não podemos esquece de remover a coluna do array de nomes de colunas
header_strings = np.delete(header_strings, 3)

In [64]:
# Nova variável na coluna de índice 3
header_strings[3]

'sub_grade'

Por fim, convertemos a variável sub_grade para sua representação numérica.

In [65]:
# Extrai os valores únicos da variável
np.unique(arr_string[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2',
       'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [66]:
# Cria uma lista da chaves
keys = list(np.unique(arr_string[:,3]))
keys[0]

'A1'

In [67]:
# Cria uma lista de valores
values = list(range(1, np.unique(arr_string[:,3]).shape[0] + 1))
values[0]

1

In [68]:
# Criamos então o dicionário
dict_sub_grade = dict(zip(keys, values))

In [69]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [70]:
# Loop ára substituit a string com as categorias pela representação numérica (frequência)
for i in np.unique(arr_string[:,3]):
    arr_string[:,3] = np.where(arr_string[:,3] == i, dict_sub_grade[i], arr_string[:,3])

In [71]:
# Extra os valores únicos da variável
np.unique(arr_string[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36', '4', '5', '6',
       '7', '8', '9'], dtype='<U69')

# Pré-Processamento da Variável Verification status com Binarização

In [72]:
# Lista com os nomes da variáveis
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [73]:
# Extrai os valores únicos da variável
np.unique(arr_string[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [74]:
# Usamos a binarização nesta variável
arr_string[:,4] = np.where((arr_string[:,4] == '') | (arr_string[:,4] == 'Not Verified'), 0, 1)

In [75]:
# Extrai os valores únicos da variável
np.unique(arr_string[:,4])

array(['0', '1'], dtype='<U69')

# Pré-Processamento da Variável url com Extração de ID

In [76]:
# Visualiza amostra dos dados
arr_string[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ..., 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [77]:
# Extraímos o id no final de cada url
np.chararray.strip(arr_string[:,5], "https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

chararray(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [78]:
# Substituímos a url pelo valor do id na url
arr_string[:,5] = np.chararray.strip(arr_string[:,5], "https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

In [79]:
# Convertemos o tipo para int32
arr_string[:,5].astype(dtype= np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [80]:
# Parece que esse id está presente na primeira coluna do conjunto de dados.
# Vamos converter para int 32 e comparar
arr_numeric[:,0].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [81]:
np.array_equal(arr_numeric[:,0].astype(dtype=np.int32), arr_string[:,5].astype(dtype=np.int32))

True

Sim, é a mesma informação. Vamos então remover uma das colunas.

In [82]:
# Remove do array de dados
arr_string = np.delete(arr_string, 5, axis=1)

In [83]:
# Remove do array de nome de coluna
header_strings = np.delete(header_strings, 5)

In [86]:
# Nova coluna no índice 5
arr_string[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [89]:
# Nova lista de colunas
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'addr_state'], dtype='<U19')

In [90]:
# Coluna ud
arr_numeric[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [91]:
# coluna id agora faz parte do array de numéricos
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

# Pré-Processamento da Variável address com Categorização

In [92]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'addr_state'], dtype='<U19')

In [94]:
# Vamos ajustar o nome da coluna
header_strings[5] = "state_address"

In [95]:
# Extrai nome e contagens
states_names, states_count = np.unique(arr_string[:,5], return_counts = True)

In [96]:
# Ordena em ordem descrescente
states_count_sorted = np.argsort(-states_count)

In [97]:
# Imprime o resultado
states_names[states_count_sorted], states_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ', 'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY', 'KS', 'OK',
        'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK', 'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,  216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,   84,   83,
          74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,   25,   24,   17,   16,   10], dtype=int64))

In [98]:
# Substituímos valores ausentes por zero
arr_string[:,5] = np.where(arr_string[:,5] == '', 0, arr_string[:,5])

Vamos separar os estads por regiões.

In [99]:
# Separamos os estados por regiões
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [101]:
# Agora substituímos cada estado pelo id da sua região
arr_string[:,5] = np.where(np.isin(arr_string[:,5], states_west), 1, arr_string[:,5])
arr_string[:,5] = np.where(np.isin(arr_string[:,5], states_south), 2, arr_string[:,5])
arr_string[:,5] = np.where(np.isin(arr_string[:,5], states_midwest), 3, arr_string[:,5])
arr_string[:,5] = np.where(np.isin(arr_string[:,5], states_east), 4, arr_string[:,5])

In [102]:
# Extrai os valores únicos
np.unique(arr_string[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

**Você pode modificar os dados, mas não pode modificar a informação!**

## Convertendo o Array

Nosso array de strings agora é um array numérico. Vamos ajustar o tipo de dado.

In [103]:
arr_string

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [104]:
arr_string = arr_string.astype(int)

In [105]:
arr_string

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [106]:
arr_string.dtype

dtype('int32')

## Checkpoint com Variáveis do Tipo String Limpas e Pré-Processadas

**Checkpoint 2**

Concluída a primeira parte, vamos gravar o checkpooint.

In [108]:
checkpooint_strings = checkpoint("Dados/Checkpoint-Strings", header_strings, arr_string)

In [109]:
checkpooint_strings["header"]

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'state_address'], dtype='<U19')

In [110]:
checkpooint_strings["data"]

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [111]:
np.array_equal(checkpooint_strings["data"], arr_string)

True

# Manipulando Colunas Numéricas

In [112]:
# Visualiza os dados
arr_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [116]:
# nomes das colunas
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [117]:
# Não temos valor ausente, pois ao carregar os dados substituídos por um valor arbitrário
np.isnan(arr_numeric).sum()

0

In [118]:
valor_coringa

68616520.0

In [119]:
# Podemos checar se uma coluna foi preenchida com o valor coringa
np.isin(arr_numeric[:,0], valor_coringa)

array([False, False, False, ..., False, False, False])

In [121]:
# Podemos checar se uma coluna foi preenchida com o valor coringa
np.isin(arr_numeric[:,0], valor_coringa).sum()

0

Vamos criar um array de estatística, especificamente valor mínimo, máximo e média de cada variável. Usaremos isso no tratament de valores ausentes (preenchidos com o valor coringa).

In [123]:
# Criamos um array com valor mínimo, média e valor máximo ignorando nan
# Usaremos isso no tratamento de valores ausentes
arr_stats = np.array([np.nanmin(dados, axis = 0), media_ignorando_nan, np.nanmax(dados, axis = 0)])


In [124]:
print(arr_stats)

[[  373332.           nan     1000.           nan     1000.           nan        6.         31.42         nan         nan         nan         nan         nan        0.  ]
 [54015809.19         nan    15273.46         nan    15311.04         nan       16.62      440.92         nan         nan         nan         nan         nan     3143.85]
 [68616519.           nan    35000.           nan    35000.           nan       28.99     1372.97         nan         nan         nan         nan         nan    41913.62]]


In [132]:
arr_stats[:, colunas_numericas]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

# Pré-Processamento da Variável funded_amnt

In [126]:
# Visualiza os dados
arr_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [127]:
arr_stats[0, colunas_numericas[2]]

1000.0

In [129]:
# Ajustamos o conteúdo da coluna
arr_numeric[:,2] = np.where(arr_numeric[:,2] == valor_coringa, arr_stats[0, colunas_numericas[2]], arr_numeric[:,2])

In [130]:
arr_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

# Pré-Processamento das Variáveis loan_amnt, int_rate, installment e total_pymnt

In [133]:
# Nomes das colunas
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [134]:
# Loop para substituir o valor ausente (valor-coringa) pelos valores do array de estatísticas
for i in [1,3,4,5]:
    arr_numeric[:,i] = np.where(arr_numeric[:,i] == valor_coringa,
                                arr_stats[2, colunas_numericas[i]],
                                arr_numeric[:,i])

In [135]:
arr_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

# Trabalhando com o Segundo Dataset
vamos carregar os dados de cotação USD - EURO. Cada linha do dataset corresponde à taxa de câmbio para um ês em um ano.

In [137]:
# Carrega o segundo dataset
dados_cot = np.genfromtxt("Dados/dataset2.csv",
                            delimiter = ',',
                            autostrip = True,
                            skip_header = 1,
                            usecols = 3)

In [138]:
# Visualiza
dados_cot

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [139]:
# nomes de colunas
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'state_address'], dtype='<U19')

In [140]:
# Dados
arr_string

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [141]:
# A coluna 0 do array de strings é o mês
arr_string[:,0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [144]:
# Vamos atribuir a coluna de mês à variável chama exchange_rate
exchange_rate = arr_string[:,0]

In [145]:
exchange_rate

array([ 5,  0,  9, ...,  6,  4, 12])

In [150]:
# Loop para preeencher a variável enchange_rate com a taxa correspondente ao mês
# Usamos dados_cot[i - 1] devido a forma como carregamos os meses para ciomportar o zero
for i in range(1, 13):
    exchange_rate = np.where(exchange_rate == i, dados_cot[i - 1], exchange_rate)

In [151]:
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [152]:
# Onde a taxa de câmbio estiver com zero substituiímos pela média
exchange_rate = np.where(exchange_rate == 0, np.mean(dados_cot), exchange_rate)

In [153]:
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [154]:
exchange_rate.shape

(10000,)

In [155]:
arr_numeric.shape

(10000, 6)

In [157]:
exchange_rate = np.reshape(exchange_rate, (10000,1))

In [158]:
# Concatenação dos arrays
arr_numeric = np.hstack((arr_numeric, exchange_rate))

In [160]:
# Inclui o nome da coluno no array de nomes de colunas
header_numeric = np.concatenate((header_numeric, np.array(['exchange_rate'])))

In [161]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'], dtype='<U19')

Vamos criar colunas para as taxas de câmbio em USD e EURO

In [162]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'], dtype='<U19')

In [163]:
# Colunas em USD
columns_dollar = np.array([1,2,4,5])

In [164]:
# Visualiza
arr_numeric[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [165]:
# Shape
arr_numeric.shape

(10000, 7)

In [166]:
# Loop pelas colunas USD para aplicar a taxa de conversão para EURO
for i in columns_dollar:
    arr_numeric = np.hstack((arr_numeric, np.reshape(arr_numeric[:,i] / arr_numeric[:,6], (10000,1))))

In [167]:
# Shape
arr_numeric.shape

(10000, 11)

In [168]:
# Visualiza
arr_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

Vamos expandir o cabeçalho com as novas colunas.

In [169]:
header_additional = np.array([column_name + '_EURO' for column_name in header_numeric[columns_dollar]])

In [170]:
header_additional

array(['loan_amnt_EURO', 'funded_amnt_EURO', 'installment_EURO', 'total_pymnt_EURO'], dtype='<U16')

In [171]:
header_numeric = np.concatenate((header_numeric, header_additional))

In [172]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate', 'loan_amnt_EURO', 'funded_amnt_EURO', 'installment_EURO', 'total_pymnt_EURO'], dtype='<U19')

In [173]:
header_numeric[columns_dollar] = np.array([column_name + '_USD' for column_name in header_numeric[columns_dollar]])

In [174]:
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD', 'exchange_rate', 'loan_amnt_EURO', 'funded_amnt_EURO', 'installment_EURO', 'total_pymnt_EURO'],
      dtype='<U19')

In [175]:
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [176]:
header_numeric = header_numeric[columns_index_order]

In [177]:
arr_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [178]:
arr_numeric = arr_numeric[:, columns_index_order]

In [179]:
arr_numeric

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

# Pré-Processamento da Variável int_rate

In [181]:
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EURO', 'funded_amnt_USD', 'funded_amnt_EURO', 'int_rate', 'installment_USD', 'installment_EURO', 'total_pymnt_USD', 'total_pymnt_EURO', 'exchange_rate'],
      dtype='<U19')

In [182]:
arr_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [183]:
# Vamos apenas dividir por 100
arr_numeric[:,5] = arr_numeric[:,5] / 100

In [184]:
arr_numeric[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

# Checkpoint com Variáveis Numéricas Limpas e Pré-Processadas
Checkpoint 3

In [185]:
checkpoint_numeric = checkpoint("Dados/Checkpoint-Numeric", header_numeric, arr_numeric)

In [186]:
checkpoint_numeric['header'], checkpoint_numeric['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EURO', 'funded_amnt_USD', 'funded_amnt_EURO', 'int_rate', 'installment_USD', 'installment_EURO', 'total_pymnt_USD', 'total_pymnt_EURO', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

# Construindo o Dataset Final

In [187]:
checkpooint_strings['data'].shape

(10000, 6)

In [188]:
checkpoint_numeric['data'].shape

(10000, 11)

In [189]:
# Concatena os arrays
df_final = np.hstack((checkpoint_numeric['data'], checkpooint_strings['data']))

In [190]:
df_final

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [191]:
# Verifica se tem valor ausente
np.isnan(df_final).sum()

0

In [192]:
# Cancatena os arrays de nomes de colunas
header_full = np.concatenate((checkpoint_numeric['header'], checkpooint_strings['header']))

In [193]:
#Ordenando o dataset
df_final = df_final[np.argsort(df_final[:,0])]

In [194]:
df_final

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [196]:
# Conferindo a ordenação da coluna 0
np.argsort(df_final[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

# Gravando o Dataset Final Limpo e Pré-Processado

In [197]:
# Concatena o array de nome de colunas com o array de dados
df_final = np.vstack((header_full, df_final))

In [198]:
# Salva em disco
np.savetxt("Dados/dataset_limpo_preprocessado.csv",
            df_final,
            fmt = '%s',
            delimiter=',')

# Fim